import io
import json
import textwrap
import time
import zipfile
from typing import Dict

import streamlit as st

from .ai_clients import claude_generate, mock_ai_frontend
from .prompt_builder import build_prompt


def generate_frontend(change_request: str = "") -> None:
    prompt = build_prompt(change_request=change_request)
    steps = [
        "Analysing brand inputs...",
        "Crafting layout structure...",
        "Applying colour palette...",
        "Generating components...",
        "Polishing typography...",
        "Finalising interactions...",
        "Building HTML output...",
        "Almost ready...",
    ]

    with st.spinner(""):
        status_el = st.empty()
        prog_el   = st.empty()

        for i, msg in enumerate(steps):
            status_el.markdown(
                f"<p style='color:#9090a8;font-size:0.88rem;margin:0'>{msg}</p>",
                unsafe_allow_html=True,
            )
            prog_el.progress(int((i + 1) / len(steps) * 100))
            time.sleep(0.18)

        if st.session_state["ai_provider"] == "Claude API":
            ok, result = claude_generate(prompt)
            if ok:
                st.session_state["generated_html"] = result
            else:
                st.warning(f"{result}  -> Falling back to Mock AI output.")
                st.session_state["generated_html"] = mock_ai_frontend(prompt)
        else:
            st.session_state["generated_html"] = mock_ai_frontend(prompt)

        status_el.empty()
        prog_el.empty()

    if change_request.strip():
        st.session_state["revision_log"].append(change_request.strip())


# â”€â”€â”€ Backend config â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def build_backend_config() -> Dict[str, str]:
    keys = [
        "google_project_id", "google_client_id", "google_client_secret",
        "google_refresh_token", "google_doc_id",
        "whatsapp_provider", "whatsapp_from", "whatsapp_to_admin",
        "email_provider", "email_host", "email_port",
        "email_user", "email_password", "admin_email",
        "payment_gateway", "payment_public_key", "payment_secret_key", "currency",
    ]
    defaults = {
        "whatsapp_provider": "Twilio",
        "email_provider": "SMTP",
        "email_port": "587",
        "payment_gateway": "Stripe",
        "currency": "USD",
    }
    return {k: str(st.session_state.get(k, defaults.get(k, ""))) for k in keys}


# â”€â”€â”€ ZIP export â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def export_zip() -> bytes:
    html     = st.session_state.get("generated_html") or mock_ai_frontend("")
    cfg      = build_backend_config()

    backend_stub = textwrap.dedent("""\
        \"\"\"
        Backend scaffold generated by AI Website Maker.
        Wire up each function to your chosen provider.
        \"\"\"
        import json
        from pathlib import Path

        CONFIG = json.loads(Path("config.json").read_text(encoding="utf-8"))


        def handle_enquiry(payload: dict) -> None:
            \"\"\"Called when a visitor submits the enquiry form.\"\"\"
            log_to_google(payload)
            send_whatsapp_alert(payload)
            send_email_alert(payload)


        def log_to_google(payload: dict) -> None:
            # TODO: use google-auth + gspread / googleapiclient to append a row
            print("Google log:", payload, "â†’ doc", CONFIG.get("google_doc_id"))


        def send_whatsapp_alert(payload: dict) -> None:
            provider = CONFIG.get("whatsapp_provider", "Twilio")
            if provider == "Twilio":
                # TODO: from twilio.rest import Client; client.messages.create(...)
                pass
            else:
                # TODO: requests.post to Meta WhatsApp Cloud API
                pass
            print(f"WhatsApp alert via {provider} to", CONFIG.get("whatsapp_to_admin"))


        def send_email_alert(payload: dict) -> None:
            import smtplib, email.mime.text as em
            # TODO: fill SMTP details from CONFIG and send
            print("Email alert to", CONFIG.get("admin_email"))


        if __name__ == "__main__":
            handle_enquiry({"name": "Test", "email": "test@example.com", "message": "Hello"})
    """)

    readme = textwrap.dedent(f"""\
        =========================================
        AI Website Maker â€“ Generated Package
        =========================================

        CONTENTS
        --------
        frontend/index.html      â€“ Your complete website (open in any browser)
        backend/config.json      â€“ All integration credentials from the wizard
        backend/backend_stub.py  â€“ Python scaffold for enquiry handling
        run_localhost.bat        â€“ Quick local preview launcher (Windows)
        README_generated.txt     â€“ This file

        QUICK START (local preview)
        ---------------------------
        1. Open a terminal in this folder.
        2. Run:  run_localhost.bat
        3. Visit http://localhost:8000 in your browser.

        BACKEND INTEGRATION
        -------------------
        The wizard collected the following categories of credentials:

        â€¢ Google (Docs/Sheets logging)
          â€“ Project ID, Client ID/Secret, Refresh Token, Target Doc/Sheet ID
          â€“ Used to append enquiry rows automatically.

        â€¢ WhatsApp alerts (Twilio or Meta Cloud API)
          â€“ Sender number, admin recipient number
          â€“ Fires a WhatsApp message on every new enquiry.

        â€¢ Email alerts (SMTP / Gmail API / SendGrid)
          â€“ SMTP host, port, username, password, admin email
          â€“ Sends an email notification to the admin on new enquiries.

        â€¢ Payment gateway (Stripe / Razorpay / PayPal)
          â€“ Public key, secret key, currency
          â€“ Integrate with your pricing cards to accept payments.

        All credentials are stored in backend/config.json.
        backend/backend_stub.py shows exactly where to insert each SDK call.

        CUSTOMISATION
        -------------
        â€¢ Edit frontend/index.html directly in any code editor.
        â€¢ Re-run the wizard and click "Apply changes" for AI-driven revisions.
        â€¢ Swap out Unsplash placeholder images for your own assets.

        DEPLOYMENT
        ----------
        â€¢ Static hosting (Netlify, Vercel, GitHub Pages): upload frontend/index.html.
        â€¢ Full-stack: attach backend_stub.py to a Flask/FastAPI server and expose
          a /enquiry POST endpoint called by the frontend form.

        Business: {st.session_state.get('business_type', 'â€”')}
        Owner:    {st.session_state.get('owner_name', 'â€”')}
        Template: {st.session_state.get('template_name', 'â€”')}
        Palette:  {st.session_state.get('palette_name', 'â€”')}
        Generated by AI Website Maker Wizard
    """)

    bat = "@echo off\ncd frontend\npython -m http.server 8000\npause\n"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("frontend/index.html", html)
        zf.writestr("backend/config.json", json.dumps(cfg, indent=2))
        zf.writestr("backend/backend_stub.py", backend_stub)
        zf.writestr("run_localhost.bat", bat)
        zf.writestr("README_generated.txt", readme)
    return buf.getvalue()



